### ISSUE TITLE
djangocms-link not setup properly in default Addon setup

### ISSUE THREAD

**Issue by stefanfoulis** [divio/djangocms-link#132]
originally reported by @digiology in divio/django-cms#6032

### Summary

The default divio project has djangocms-link's LinkPlugin installed. However the settings file is missing `DJANGOCMS_LINK_USE_SELECT2 = True` which results in the Internal Link dropdown being empty without any errors or explanation.

#### Environment

* Python version: 2.7.13
* Django version: 1.8.18.1
* django CMS version: 3.4.4.2

### Fix
Needs to be fixed in ``aldryn_config.py``

**Comment by czpython** [comment]
I think select2 is not the problem here.
When `DJANGOCMS_LINK_USE_SELECT2` is set to False (the default), we use django's standard <select> widget. Setting `DJANGOCMS_LINK_USE_SELECT2` to True seems to fix the problem because a different widget is used but the real issue is with the default. On the cloud this setting is not set because of backwards incompatibility issues with select2 versions (if I recall correctly).

**Comment by vxsx** [comment]
This ticket doesn't state this, but the problem is in IE11, and https://github.com/divio/django-cms/pull/6041 is a bugfix for this (will backport to 3.4.x soon)

**Comment by vxsx** [comment]
https://github.com/divio/django-cms/pull/6042 backport
